// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzTseEfP5-sPYscY2kM5wD0S2kz1UznJU',
    appId: '1:1043077299115:web:0f396d7c5964c4fc90f0ee',
    messagingSenderId: '1043077299115',
    projectId: 'groupchat-2ba1a',
    authDomain: 'groupchat-2ba1a.firebaseapp.com',
    databaseURL: 'https://groupchat-2ba1a-default-rtdb.firebaseio.com',
    storageBucket: 'groupchat-2ba1a.appspot.com',
    measurementId: 'G-DM6EGFBB79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASQvDTkuGiQYYOy8Hj0A4MkeBvk-sgiBg',
    appId: '1:1043077299115:android:1f1ced6817069cc290f0ee',
    messagingSenderId: '1043077299115',
    projectId: 'groupchat-2ba1a',
    databaseURL: 'https://groupchat-2ba1a-default-rtdb.firebaseio.com',
    storageBucket: 'groupchat-2ba1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEQSmM8zAxIUNaRzacJj7isxC5TzFMUkE',
    appId: '1:1043077299115:ios:dcf405c5d28b934290f0ee',
    messagingSenderId: '1043077299115',
    projectId: 'groupchat-2ba1a',
    databaseURL: 'https://groupchat-2ba1a-default-rtdb.firebaseio.com',
    storageBucket: 'groupchat-2ba1a.appspot.com',
    iosClientId: '1043077299115-v0sd81l6qht0srcqtmgvc5e0o54dghtm.apps.googleusercontent.com',
    iosBundleId: 'com.rayyuan.GroupChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEQSmM8zAxIUNaRzacJj7isxC5TzFMUkE',
    appId: '1:1043077299115:ios:69ac627469ed915d90f0ee',
    messagingSenderId: '1043077299115',
    projectId: 'groupchat-2ba1a',
    databaseURL: 'https://groupchat-2ba1a-default-rtdb.firebaseio.com',
    storageBucket: 'groupchat-2ba1a.appspot.com',
    iosClientId: '1043077299115-c0rk95jpu2rppf5c4haeick0ln0ibi0e.apps.googleusercontent.com',
    iosBundleId: 'com.rayyuan.groupChat',
  );
}
